# -*- coding: utf-8 -*-
"""Actividad de taller 1.2.1_Daniel_Santos_Mendez.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vMpUya--YK6_eSl_qj7n6Zy_OYDV_uzY

Primera Parte: Calcular area, volumen o perimetro de figuras geometricas
"""

import math

"""Cuadrado"""

a = int(input("Ingrese el lado del cuadrado: \n"))

print(f"Area = {a*a}\nPerimetro = {4*a}")

"""Triangulo"""

a = int(input("Ingrese el lado 'a' del triangulo: \n"))
b = int(input("Ingrese el lado 'b' del triangulo: \n"))
c = int(input("Ingrese el lado 'c' del triangulo: \n"))
base = int(input("Ingrese la base del triangulo: \n"))
h = int(input("Ingrese la altura del triangulo: \n"))

print(f"Area = {(base*h)/2}\nPerimetro = {a+b+c}")

"""Rectangulo"""

a = int(input("Ingrese el lado 'a' del Rectangulo: \n"))
b = int(input("Ingrese el lado 'b' del Rectangulo: \n"))


print(f"Area = {b*a}\nPerimetro = {2*(b+a)}")

"""Paralelogramo"""

a = int(input("Ingrese el lado 'a' del Paralelogramo: \n"))
b = int(input("Ingrese el lado 'b' del Paralelogramo: \n"))
h = int(input("Ingrese h del Paralelogramo: \n"))

print(f"Area = {b*a}\nPerimetro = {2*(b+a)}")

"""Rombo"""

D = int(input("Ingrese D: \n"))
d = int(input("Ingrese d: \n"))
a = int(input("Ingrese a: \n"))

print(f"Area = {(D*d)/2}\nPerimetro = {4*a}")

"""Cometa"""

D = int(input("Ingrese D: \n"))
d = int(input("Ingrese d: \n"))
a = int(input("Ingrese a: \n"))
b = int(input("Ingrese b: \n"))

print(f"Area = {(D*d)/2}\nPerimetro = {2*(b+a)}")

"""Trapecio"""

B = int(input("Ingrese D: \n"))
b = int(input("Ingrese d: \n"))
h = int(input("Ingrese h: \n"))
a = int(input("Ingrese a: \n"))
c = int(input("Ingrese c: \n"))

print(f"Area = {((B+b)*h)/2}\nPerimetro = {B+b+a+c}")

"""Circulo"""

r = int(input("Ingrese r: \n"))


print(f"Area = {math.pi*math.pow(r,2)}\nPerimetro = {2*math.pi*r}")

"""Poligono regular"""

n = int(input("Ingrese n: \n"))
a = int(input("Ingrese a: \n"))
b = int(input("Ingrese b: \n"))

print(f"Area = {(n*b*a)/2}\nPerimetro = {n*b}")

"""Corona circular"""

R = int(input("Ingrese R: \n"))
r = int(input("Ingrese a: \n"))

print(f"Area = {math.pi * (math.pow(R,2)-math.pow(r,2))  }\n")

"""Sector circular"""

R = int(input("Ingrese R: \n"))
n = int(input("Ingrese n: \n"))

print(f"Area = {(math.pi * math.pow(R,2) * n)/360  }\n")

"""Cubo"""

a = int(input("Ingrese a: \n"))

print(f"Area = {6 * math.pow(a,2)  }\nVolumen = {math.pow(a,3)}")

"""Cilindro"""

h = int(input("Ingrese h: \n"))
R = int(input("Ingrese R: \n"))

print(f"Area = {2*math.pi*R*(h+R)}\nVolumen = {math.pi*math.pow(R,2)*h}")